
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
Prisma.prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CompanyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  domain: 'domain',
  createdAt: 'createdAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  companyId: 'companyId',
  role: 'role',
  createdAt: 'createdAt'
};

exports.Prisma.CompanyIntegrationScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  service: 'service',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.ImapCredentialScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  imapHost: 'imapHost',
  imapPort: 'imapPort',
  emailAddress: 'emailAddress',
  encryptedPassword: 'encryptedPassword',
  useTls: 'useTls',
  createdAt: 'createdAt'
};

exports.Prisma.CustomerScalarFieldEnum = {
  id: 'id',
  fortnoxCustomerNumber: 'fortnoxCustomerNumber',
  name: 'name',
  email: 'email',
  domain: 'domain',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.EmployeeCustomerScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  customerId: 'customerId',
  assignedAt: 'assignedAt',
  assignedBy: 'assignedBy'
};

exports.Prisma.TimeEntryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  customerId: 'customerId',
  date: 'date',
  hours: 'hours',
  description: 'description',
  source: 'source',
  rawCustomerName: 'rawCustomerName',
  createdAt: 'createdAt'
};

exports.Prisma.EmailActivityScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  customerId: 'customerId',
  sentAt: 'sentAt',
  recipientEmail: 'recipientEmail',
  recipientDomain: 'recipientDomain',
  subject: 'subject',
  messageId: 'messageId',
  createdAt: 'createdAt'
};

exports.Prisma.EmailScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  source: 'source',
  imapCredentialId: 'imapCredentialId',
  userId: 'userId',
  customerId: 'customerId',
  direction: 'direction',
  subject: 'subject',
  fromAddress: 'fromAddress',
  fromName: 'fromName',
  toAddresses: 'toAddresses',
  ccAddresses: 'ccAddresses',
  bccAddresses: 'bccAddresses',
  replyTo: 'replyTo',
  sentAt: 'sentAt',
  bodyText: 'bodyText',
  bodyHtml: 'bodyHtml',
  inReplyTo: 'inReplyTo',
  threadId: 'threadId',
  mailbox: 'mailbox',
  createdAt: 'createdAt'
};

exports.Prisma.FortnoxCustomerScalarFieldEnum = {
  id: 'id',
  customerNumber: 'customerNumber',
  customerId: 'customerId',
  name: 'name',
  organisationNumber: 'organisationNumber',
  email: 'email',
  phone: 'phone',
  address: 'address',
  zipCode: 'zipCode',
  city: 'city',
  country: 'country',
  currency: 'currency',
  active: 'active',
  rawData: 'rawData',
  syncedAt: 'syncedAt',
  createdAt: 'createdAt'
};

exports.Prisma.FortnoxInvoiceScalarFieldEnum = {
  id: 'id',
  invoiceNumber: 'invoiceNumber',
  customerNumber: 'customerNumber',
  customerId: 'customerId',
  invoiceDate: 'invoiceDate',
  dueDate: 'dueDate',
  totalExclVat: 'totalExclVat',
  totalInclVat: 'totalInclVat',
  vat: 'vat',
  currency: 'currency',
  status: 'status',
  ourReference: 'ourReference',
  yourReference: 'yourReference',
  sentAt: 'sentAt',
  rawData: 'rawData',
  syncedAt: 'syncedAt',
  createdAt: 'createdAt'
};

exports.Prisma.FortnoxInvoiceRowScalarFieldEnum = {
  id: 'id',
  invoiceNumber: 'invoiceNumber',
  rowNumber: 'rowNumber',
  articleNumber: 'articleNumber',
  description: 'description',
  quantity: 'quantity',
  price: 'price',
  vatPercent: 'vatPercent',
  total: 'total'
};

exports.Prisma.InvoiceRecipientAliasScalarFieldEnum = {
  id: 'id',
  alias: 'alias',
  customerId: 'customerId',
  createdAt: 'createdAt'
};

exports.Prisma.FortnoxSyncLogScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  resource: 'resource',
  lastSyncedAt: 'lastSyncedAt'
};

exports.Prisma.FortnoxFinancialYearScalarFieldEnum = {
  id: 'id',
  fortnoxId: 'fortnoxId',
  fromDate: 'fromDate',
  toDate: 'toDate',
  accountChartType: 'accountChartType',
  accountingMethod: 'accountingMethod',
  rawData: 'rawData',
  syncedAt: 'syncedAt',
  createdAt: 'createdAt'
};

exports.Prisma.FortnoxAccountScalarFieldEnum = {
  id: 'id',
  accountNumber: 'accountNumber',
  financialYearId: 'financialYearId',
  description: 'description',
  active: 'active',
  balanceBroughtForward: 'balanceBroughtForward',
  balanceCarriedForward: 'balanceCarriedForward',
  vatCode: 'vatCode',
  sru: 'sru',
  rawData: 'rawData',
  syncedAt: 'syncedAt',
  createdAt: 'createdAt'
};

exports.Prisma.FortnoxVoucherScalarFieldEnum = {
  id: 'id',
  voucherSeries: 'voucherSeries',
  voucherNumber: 'voucherNumber',
  financialYearId: 'financialYearId',
  transactionDate: 'transactionDate',
  description: 'description',
  referenceType: 'referenceType',
  referenceNumber: 'referenceNumber',
  costCenter: 'costCenter',
  project: 'project',
  approvalState: 'approvalState',
  rawData: 'rawData',
  syncedAt: 'syncedAt',
  createdAt: 'createdAt'
};

exports.Prisma.FortnoxVoucherRowScalarFieldEnum = {
  id: 'id',
  voucherId: 'voucherId',
  accountNumber: 'accountNumber',
  debit: 'debit',
  credit: 'credit',
  description: 'description',
  costCenter: 'costCenter',
  project: 'project'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  Company: 'Company',
  User: 'User',
  CompanyIntegration: 'CompanyIntegration',
  ImapCredential: 'ImapCredential',
  Customer: 'Customer',
  EmployeeCustomer: 'EmployeeCustomer',
  TimeEntry: 'TimeEntry',
  EmailActivity: 'EmailActivity',
  Email: 'Email',
  FortnoxCustomer: 'FortnoxCustomer',
  FortnoxInvoice: 'FortnoxInvoice',
  FortnoxInvoiceRow: 'FortnoxInvoiceRow',
  InvoiceRecipientAlias: 'InvoiceRecipientAlias',
  FortnoxSyncLog: 'FortnoxSyncLog',
  FortnoxFinancialYear: 'FortnoxFinancialYear',
  FortnoxAccount: 'FortnoxAccount',
  FortnoxVoucher: 'FortnoxVoucher',
  FortnoxVoucherRow: 'FortnoxVoucherRow'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
